// vue/to-do-app/src/components/todos/TodoItem.vue
<template>
    <v-list-item>
        <template v-slot:prepend>
            <v-btn 
                :icon="todo.isCompleted ? 'mdi-check-circle' : 'mdi-circle-outline'"
                variant="text" 
                size="small" 
                @click="() => $emit('completeTodo')" 
            />
            <v-avatar :size="34" v-if="todo.image">
                <v-img :src="todo.image" />
            </v-avatar>
        </template>

        <v-list-item-title>
            <div :class="{ 'text-decoration-line-through blurred': todo.isCompleted }">
                <span>{{ todo.text }}</span>
                <br />
                <v-chip 
                    v-if="todo.tags.length > 0"
                    v-for="tag in todo.tags" 
                    :key="tag"
                    size="x-small"
                    variant="tonal"
                    color="blue-grey"
                > 
                    {{ tag }}
                </v-chip>

                <v-chip 
                    v-if="todo.file"
                    size="x-small"
                    variant="tonal"
                    color="dark-grey"
                    class="ma-2"
                    label
                    @click="downloadFile(todo.file)"
                > 
                    <v-icon icon="mdi-download" start></v-icon>
                    {{ todo?.file?.split('/').pop() }}
                </v-chip>
            </div>
        </v-list-item-title>
        
        <template v-slot:append>
            <v-btn color="red-lighten-1" icon="mdi-delete" variant="text" size="small" @click="() => $emit('removeTodo')" />
            <v-btn color="blue-lighten-1" icon="mdi-pencil" variant="text" size="small" @click="() => $emit('editTodo')" />
        </template>
    </v-list-item>
</template>

<script setup>
import fileDownload from 'js-file-download';


const props = defineProps({
    todo: Object
})

const downloadFile = (file) => {
    fileDownload(file, file.split('/').pop());
}

</script>

<style lang="scss" scoped>
.blurred {
  filter: blur(0.5px);
}
</style>

// react/to-do-app/src/components/todos/TodoItem.jsx
import React from 'react'
import DeleteIcon from '@mui/icons-material/Delete';
import RadioButtonUncheckedIcon from '@mui/icons-material/RadioButtonUnchecked';
import RadioButtonCheckedIcon from '@mui/icons-material/RadioButtonChecked';
import EditIcon from '@mui/icons-material/Edit';
import ArrowCircleDownIcon from '@mui/icons-material/ArrowCircleDown';
import { List, ListItem, ListItemButton, ListItemIcon, ListItemText, IconButton, Chip, Button } from '@mui/material';
import fileDownload from 'js-file-download';

export default function TodoItem({ todo, completeTodo, editTodo, removeTodo }) {

  const downloadFile = (file) => {
    fileDownload(file, file.split('/').pop());
  }

  return (
    <>
      <List
        sx={{ width: '100%', bgcolor: 'background.paper' }}
        component="nav"
        aria-label="main mailbox folders"
      >
        <ListItem>
          <ListItemButton>
            <ListItemIcon>
              <IconButton edge="start" onClick={() => completeTodo(todo._id)}>
                {todo?.isCompleted ? <RadioButtonCheckedIcon /> : <RadioButtonUncheckedIcon />}
              </IconButton>
            </ListItemIcon>

            <span style={{ marginRight: "5px" }}>
              {todo?.image ? <img src={todo?.image} alt="thumbnail" width={32} height={32} className="rounded-full"  /> : ""}
            </span>

            <ListItemText>
              <span className={`${todo?.isCompleted ? "line-through" : ""}`}>
                {todo?.text}
              </span>
              <br />
              {todo?.tags?.length > 0 ? 
                todo.tags.map(tag => (
                  <Chip key={tag} label={tag} size="small" />
                ))
                : ""
              } 


                {todo?.file &&
                  typeof todo.file === 'string' &&  
                  todo.file.split('/').pop() && 
                  <Button onClick={() => downloadFile(todo?.file)}>
                    <ArrowCircleDownIcon />
                    {todo?.file?.split('/').pop()}
                  </Button>
                }
            </ListItemText>

            <IconButton edge="end" aria-label="delete" color="error" onClick={() => removeTodo(todo._id)}>
              <DeleteIcon />
            </IconButton>

            <IconButton edge="end" aria-label="edit" color="primary" onClick={() => editTodo(todo)}>
              <EditIcon />
            </IconButton>
          </ListItemButton>
        </ListItem>
      </List>
    </>
  )
}
